feat: add core library
francis36012/code-challenge-teleport-systems-l3 pull request #2
Opened 2021-11-22 19:37 UTC by francis36012

Add the core library functionality.

**Please Note**: Tests will be added later

2021-11-22 22:23 UTC, timothyb89 requested changes
It seems like there's quite a few issues around locking. From a design perspective, there's a pretty surprising number of locks to manage in the system. Perhaps a simpler design using fewer locks could help eliminate some of these issues?

2021-11-22 22:23 UTC, timothyb89 commented on core/inmem_worker.go
> +			job.cmd.Process.Kill()
This error should be handled

2021-11-22 22:23 UTC, timothyb89 commented on core/worker.go
> +	GetJobsByStatus(status JobStatus) ([]*Job, error)
Just a nitpick, but this API function isn't necessarily required.

2021-11-22 22:23 UTC, timothyb89 commented on core/inmem_worker.go
> +	result := make([]*Job, 0, len(w.storage.jobs))
We need a lock to safely read from these jobs.

2021-11-22 22:23 UTC, timothyb89 commented on core/inmem_worker.go
> +	}
A lock is needed here as well.

2021-11-22 22:23 UTC, timothyb89 commented on core/inmem_worker.go
> +			out := w.storage.stdoutBuffer[job.ID]
We need locks to guard access to these maps (and below for the stderr variant as well)

2021-11-23 19:54 UTC, francis36012 commented on core/inmem_worker.go
> +func (w *inMemWorker) GetJobStderrStreaming(id JobID) (chan []byte, error) {
The implementations for stdout and stderr have been combined

2021-11-23 19:56 UTC, francis36012 commented on core/inmem_worker.go
> +		jobLock := w.perJobLocks[jobID]
The mutex copy issue has been fixed

2021-11-24 10:47 UTC, smallinsky commented on core/inmem_worker.go
> +	perJobLocks       map[JobID]*sync.RWMutex
Why not move this to Job struct

2021-11-24 10:47 UTC, smallinsky commented on core/inmem_worker.go
> +	perJobStderrLocks       map[JobID]*sync.RWMutex
Does `inMemWorker` is best place for stderr and stdout fields. Did you consider moving these field to Job struct ?

2021-11-24 10:47 UTC, smallinsky commented on core/inmem_worker.go
> +		return nil, nil
Why not NotFound - returning nil object and nil error is general not good idea.

2021-11-24 10:47 UTC, smallinsky commented on core/inmem_worker.go
> +	return job, nil
Data race - when a job is returned to the library user and for example user calls job.FinishedAt  without any lock.

2021-11-24 14:44 UTC, francis36012 commented on core/inmem_worker.go
> +	perJobStderrLocks       map[JobID]*sync.RWMutex
I hadn't thought of that but now that you mentioned it, I think moving them into the Job struct will make things simpler and clearer - in most scenarios, we already have a job object around where they are used. Doing so should also make some of the locks unnecessary

2021-11-24 14:53 UTC, francis36012 commented on core/inmem_worker.go
> +		return nil, nil
You're right, having NotFound here will make the result be a little more clearer to the caller - I returned nil, nil here because I thought the job not being found shouldn't be considered an error (that should have been communicated in the method's doc comments).

2021-11-24 14:58 UTC, francis36012 commented on core/inmem_worker.go
> +	return job, nil
My bad (missed it in all the accessors). I think return a copy of the job here will be the safest option - what do you think?

2021-11-24 20:00 UTC, r0mant commented on core/inmem_worker.go
> +	jobsMapLock       *sync.RWMutex
Nit: None of these locks need to be pointers (same throughout).
```suggestion
	jobsMapLock       sync.RWMutex
```

2021-11-24 20:00 UTC, r0mant commented on core/inmem_worker.go
> +	defer w.perJobStderrLockMapLock.Unlock()
There's a lot of locking going on so it's quite hard to understand what all these locks are for. Any way to refactor the library in a way that doesn't require you so lock/unlock 6 different mutexes to create a job or stream the logs?

2021-11-24 20:00 UTC, r0mant commented on core/inmem_worker.go
> +	w.newJobRequestQueue <- &job
Any reason you're not just starting the job right away instead of placing it into queue?

2021-11-25 00:23 UTC, francis36012 commented on core/inmem_worker.go
> +	w.newJobRequestQueue <- &job
There wasn't any reason in particular

2021-11-25 00:24 UTC, francis36012 commented on core/inmem_worker.go
> +	defer w.perJobStderrLockMapLock.Unlock()
The code has been updated to reduce the number of locks used

2021-11-25 00:24 UTC, francis36012 commented on core/inmem_worker.go
> +	jobsMapLock       *sync.RWMutex
Suggestion has been applied

2021-11-25 00:25 UTC, francis36012 commented on core/inmem_worker.go
> +		return nil, nil
This method will now return the zero value for Job and ErrNotFound if the job isn't found

2021-11-25 00:26 UTC, francis36012 commented on core/inmem_worker.go
> +	perJobStderrLocks       map[JobID]*sync.RWMutex
These have now been moved into Job struct

2021-11-29 23:37 UTC, timothyb89 commented on core/inmem_worker.go
> +		req.outChannel <- data
Hmm, this works but it seems like it effectively busy loops. Anyone listening on the channel will get constant empty `[]byte` messages, and the CPU usage gets quite high if there's more than a couple listeners (10 streams eats up 3 cores on my box while running `sleep`)

Maybe there's a different strategy to, say, wait until a bit of data comes in rather than busy looping?

2021-11-30 19:36 UTC, merged